### ISSUE TITLE
wget 不是 macos 默认自带工具, 在build.sh需判断是否存在

### ISSUE THREAD

**Issue by zeroleo12345** [Ryan-Miao/docker-yapi#1]
导致build镜像的时候报错, 错误提示不太友好
Step 4/16 : ADD yapi.tgz /home/
ADD failed: stat /var/lib/docker/tmp/docker-builder468713448/yapi.tgz: no such file or directory
Error response from daemon: No such image: yapi:latest

**Comment by Ryan-Miao** [comment]
已添加错误提示  see https://github.com/Ryan-Miao/docker-yapi/commit/7737e7e68f7eb904742c8cadddfcbc27c63808c1
