### ISSUE TITLE
镜像build了好多次, 模块找不到

### ISSUE THREAD

**Issue by kackerx** [Ryan-Miao/docker-yapi#11]
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/my-yapi/vendors/server/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

镜像build了好多次, 模块找不到

**Comment by chenuy** [comment]
第一次修改docker-compose.yml里的command指令

**Comment by ScutRukawa** [comment]
你知道这个app.js 的位置在哪吗

**Comment by ScutRukawa** [comment]
你知道这个app.js 的位置在哪吗

**Comment by caoxuexi** [comment]
我也是这个问题，老哥问题解决了吗

**Comment by Ryan-Miao** [comment]
你点安装的时候安装到哪里了就在哪里，和官网cli安装一样啊，这里的docker只是提供了环境而已，你仔细看命令

**Comment by caoxuexi** [comment]
> 你点安装的时候安装到哪里了就在哪里，和官网cli安装一样啊，这里的docker只是提供了环境而已，你仔细看命令

我按照老哥你那个说明走的三个步骤
·git clone https://github.com/Ryan-Miao/docker-yapi.git
·cd docker-yapi 
·docker-compose up
然后报的上面这个Error: Cannot find module '/my-yapi/vendors/server/app.js'   错误

**Comment by caoxuexi** [comment]
> 第一次修改docker-compose.yml里的command指令

怎么修改诶，能说明一下吗？拜托了

**Comment by Ryan-Miao** [comment]
yapi:
    build:
      context: ./
      dockerfile: Dockerfile
    image: yapi
    # 第一次启动使用
    # command: "yapi server"
    # 之后使用下面的命令
    command: "node /my-yapi/vendors/server/app.js"

**Comment by Icecream-2018** [comment]
> > 第一次修改docker-compose.yml里的command指令
> 
> 怎么修改诶，能说明一下吗？拜托了

我也遇到这个问题 完全不知道怎么办

**Comment by mrhelloboy** [comment]
@Icecream-2018 
在第一次执行 `docker-compose up` 命令之前，修改docker-compose.yml文件，将 `#command: "yapi server"` 的注释去掉，将`command: "node /my-yapi/vendors/server/app.js"`这行注释。然后再执行 `docker-compose up`。部署完之后，再改回来。

**Comment by wjh791072385** [comment]
> @Icecream-2018 在第一次执行 `docker-compose up` 命令之前，修改docker-compose.yml文件，将 `#command: "yapi server"` 的注释去掉，将`command: "node /my-yapi/vendors/server/app.js"`这行注释。然后再执行 `docker-compose up`。部署完之后，再改回来。

确实解决了，感谢，不过为什么yml文件一开始不初始成那样....readme也不说明下。。

**Comment by DreamBizideal** [comment]
我也遇到了这个问题  感谢各位大佬

**Comment by kackerx** [comment]
e, ,
