### ISSUE TITLE
如何安装插件？

### ISSUE THREAD

**Issue by HasonHuang** [Ryan-Miao/docker-yapi#3]
**问题：** 

请问如何安装插件？（例如：钉钉）

**环境：**
- Yapi 1.9.1
- 这个仓库的 Dockerfile
- 插件 [钉钉](https://github.com/zgs225/yapi-plugin-dding)

**Comment by dybxin** [comment]
同问，该方式支持插件吗?

**Comment by Ryan-Miao** [comment]
按照官方文档安装即可, 已经更新为官方部署方案
