### ISSUE TITLE
请问npm的时候为什么我卡住不动了呢？

### ISSUE THREAD

**Issue by ohohok** [Ryan-Miao/docker-yapi#4]
Building yapi
Step 1/4 : FROM node:12-alpine
 ---> 057fa4cc38c2
Step 2/4 : COPY repositories /etc/apk/repositories
 ---> Using cache
 ---> 3c404293437f
Step 3/4 : RUN  npm install -g yapi-cli --registry https://registry.npm.taobao.org
 ---> Running in 1b16396feb05

**Comment by Ryan-Miao** [comment]
自己进入容器排查
```
docker run -it node:12-alpine /bin/bash
```

![image](https://user-images.githubusercontent.com/11866078/88766999-90f7e780-d1ab-11ea-93e3-28837ec5fbf9.png)

**Comment by Ryan-Miao** [comment]
也可以直接进入你卡着的那个部分, 比如你的
Step 3/4 : RUN npm install -g yapi-cli --registry https://registry.npm.taobao.org
---> Running in 1b16396feb05

docker exec -it 1b16396feb05  sh

**Comment by CloverQ** [comment]
我也遇到这个问题了，重启一下虚拟机然后运行docker compose up就好了
