### ISSUE TITLE
部署失败，报错两个错误，一个错误是yapi.demo.qunar.com失效，一个是无效连接数据库

### ISSUE THREAD

**Issue by chensonghiter** [Ryan-Miao/docker-yapi#8]
yapi_1   | 在浏览器打开 http://0.0.0.0:9090 访问。非本地服务器，请将 0.0.0.0 替换成指定的域名或ip 
yapi_1   | (node:1) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND yapi.demo.qunar.com
yapi_1   |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
yapi_1   | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
yapi_1   | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
yapi_1   | 当前安装版本： 1.9.2
yapi_1   | Error:  连接数据库失败, failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
yapi_1   |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16) {
yapi_1   |   name: 'MongoError'
yapi_1   | }]

**Comment by Ryan-Miao** [comment]
参照readme
